Fix the bug in compare value
open-iscsi/open-isns pull request #42
Opened 2024-02-02 05:19 UTC by cossbow

GCC fill zero in padding bits in struct and union are undifined behavior to C std, and clang not do this. So if we use clang to compile code, we will see the error result of comparing isns_value_t.

2024-02-02 05:20 UTC, cossbow commented
I referred the doc at https://wiki.sei.cmu.edu/confluence/display/c/EXP42-C.+Do+not+compare+padding+data.

2024-02-12 17:18 UTC, gonzoleeman requested changes
Please update the comment to include the error message you see with clang before this change. Otherwise, looks good to me.

2024-02-24 03:11 UTC, cossbow commented
> Please update the comment to include the error message you see with clang before this change. Otherwise, looks good to me.

This error not happen in compiling, but in running. If I compile open-isns with clang, I can see this (May not be visible on all machines):
`[root@localhost build-open-isns]# ./isnsadm -c config1 --local --dd-register member-name=isns.client1 member-name=isns.client2
Registered DD:
  0811  uint32      : DD ID = 1
  0812  string      : DD name = "isns.dd1"
  081e  uint32      : DD features = <NIL>
  0813  uint32      : DD member iSCSI index = 5
  0814  string      : DD member iSCSI name = "isns.client1"
  0813  uint32      : DD member iSCSI index = 9
  0814  string      : DD member iSCSI name = "isns.client2"
[root@localhost build-open-isns]# ./isnsadm -c config1 --list dds 
[root@localhost build-open-isns]# 
`
Here if I restart isnsd, command [./isnsadm -c config1 --list dds] will print write results.
Here is a simple case:
`
#include <stdio.h>
#include <stdint.h>

typedef union {
    int8_t  i8;
    int16_t i16;
    int32_t i32;
    int64_t i64;
} GenValue;

int main()
{
    char buf[1024]; // force stack offset 1K

    uint32_t value = 1;
    GenValue var = {.i8 = value};
    printf("i8 =%d, i16=%d, i32=%d, i64=%ld\n", var.i8, var.i16, var.i32, var.i64);

    return 0;
}
`
I use gcc to compile and run, the result is what I expected: 
`[root@localhost sample]# gcc main.c 
[root@localhost sample]# ./a.out 
i8 =1, i16=1, i32=1, i64=1
`
And use clang:
`[root@localhost sample]# clang main.c 
[root@localhost sample]# ./a.out 
i8 =1, i16=-255, i32=-255, i64=4294967041
`
Compare all bits in struct and union is depend undefined behavior (see: https://wiki.sei.cmu.edu/confluence/display/c/EXP42-C.+Do+not+compare+padding+data).

This PR is one of the solutions, we also can use memset() to init before use.

2024-02-26 19:48 UTC, gonzoleeman commented
Hi @cossbow -- I apologize for taking a while to evaluate this. I appreciate your detailed explanation.

I looked over the link you provided, and I wish it had more info. So I took your example program and compiled it on my aarch64 (AMD) kernel. Very interesting. My program is much like yours. Here's the output using clang:
```
var_a (expect   1): i8=1, i16=-32511, i32=-907378431, i64=281474069332225
var_b (expect 127): i8=127, i16=-129, i32=-129, i64=4294967167

After update of var_b to var_a value:
var_a (expect   1): i8=1, i16=-32511, i32=-907378431, i64=281474069332225
var_b (expect   1): i8=1, i16=-255, i32=-255, i64=4294967041

Is var_a == var_b? (they should be)
  var_a.i8  == var_b.i8
  var_a.i16  < var_b.i16	oh oh
  var_a.i32  < var_b.i32	oh oh
  var_a.i64  > var_b.i64	oh oh
```
This is setting "var_a.i8 = 1", "var_b.i8 = 12u", then "var_b.i8 = 1".

All of this works fine using C, of course. But not with clang. :)

My concern is that your changes don't go far enough. You modified how compares are done for equality, but not for greater than or less than (inequality). Notice how my test shows great variation in comparison results.

In my testing, if I change one thing, I fix the problem. That is to clear out the whole union (with memset(0)) before assigning any value to any of its incarnations.

So if I do:
```
    var_a.i8 = 1
```
I have this problem. But if I do:
```
    memset(&var_a, 0, sizeof(var_a));
    var_a.i8 = 1
```
It works fine.

It's interesting, though, that your testing showed that your changes fixed your problem.

I will post my test program separately.

2024-03-15 08:04 UTC, cossbow commented
Hi @gonzoleeman -- I thought about memset, but I saw a lot of initialization code, but it's another train of thought, and I'm only going to try the first one O(∩_∩)O哈哈~.
The inequality, I thought it was just for sorting, so I just did a quick comparison. My method may not be suitable.

2024-03-20 05:22 UTC, cossbow commented
I make another patch, which direct fill zero in isns_value_t initialization.
#43

2024-03-27 10:34 UTC, closed without merging

2024-03-27 10:35 UTC, cossbow commented
I suggest pr https://github.com/open-iscsi/open-isns/pull/43